### ISSUE TITLE
Missing .gitmodules file

### ISSUE THREAD

**Issue by antoine-pous** [dannyvankooten/vimrc#1]
I really love the idea to provide an all in one for VIM config :+1: 

Currently on your configuration you should use .gitmodules file, so you can clone directly this repository in replacement of `~/.vim`.

With this approach you can clone and maintain your plugins painless.

**Comment by dannyvankooten** [comment]
Hey @antoine-pous,

Was just thinking that yesterday too. Haven't got around to it yet but will be needing this for my other devices anyway so hopefully can get to it soon enough!
